[View in Colaboratory](https://colab.research.google.com/github/yurrr/APSP-e-matrizes-de-adjac-ncia/blob/master/final.ipynb)


##Grafos e Matrizes de adjacência


### Yuri Medeiros da Silva  - 117061898 
---

A ideia do trabalho é apresentar uma solução ao problema do **APSP¹**  usando multiplicação de matrizes de adjacência. 

Utilizaremos o Algoritmo de Djikstra³ **( SSSP² )** como forma de comparação com o método de potenciação de matrizes de adjacencia(APSP, comparando os resultados e os tempos obtidos.

¹ All Pair Shortest path , todos os menores caminhos para todos os vértices

² Single source shortest path, os menores caminhos partindo de um vértice específico

³ Apesar de ser utilizado para encontrar todos os melhores caminhos a partir de um vértice , conseguimos utilizar Djikistra para todos encontrar o APSP executando-o mais de uma vez.


Explicações mais detalhadas sobre os tópicos abordados aqui podem ser encontradas no documento abaixo

 [Notas APSP e matrizes de adjacência](https://docs.google.com/document/d/1smSD6Us7K-WID6jXzlJF5M-d4Qy-yL9a2vpdnUeQjoE/edit?usp=sharing)









In [25]:
#necessary imports
import math
import time
import numpy as np
import scipy
from scipy import linalg

##Dijkstra

> ![grafo](https://i.imgur.com/xRx4syf.jpg)



> Dijkstra é utilizado para  a partir de um nó raize encontrarmos o melhor - menos custoso - caminho até os outros vértices.

> Pelo exemplo, teriamos que os melhores caminhos partindo de $a$ seriam :

>> $a \rightarrow c$  tem peso 2

>> $a \rightarrow b$   tem peso 3. Indo de $a \rightarrow c \rightarrow b$. 

¹ onde não necessariamente o melhor caminho é o  "mais direto"






###Dijkstra algoritmo
Input : 
>O algorítmo recebe uma matriz de adjacência¹ e o vértice a partir do qual serão calculados os caminhos ,respectivamente Graph e source

Output :
> Um vetor com os caminhos mais curtos a partir do vértice $source$



¹ Representação de um grafo sem arestas negativas
² A explicação mais detalhada do algorítmo, incluindo pseudo-codigo, pode ser encontrada no link [Notas APSP e matrizes de adjacência](https://docs.google.com/document/d/1smSD6Us7K-WID6jXzlJF5M-d4Qy-yL9a2vpdnUeQjoE/edit?usp=sharing)


In [26]:
# Gets min distance between the adjacent nodes
# This is a sub-routine utilized in Dijkstra algorithm
def distMin(Graph,dist,Q):
  each,res,n= math.inf, -1, len(Graph)
  for v in range(n) : 
    if dist[v] < each and Q[v] == False:
      each = dist[v]
      res = v
  return res

In [27]:
# Dijkstra
# Based on wikipedia pseudocode
# calculates the shortest path on a Graph 
# from a vertex 'source' to all other nodes
def dijkstra(Graph, source) :
  # distance to all vertices is inf. 
  # distance from source node to itself is 0 
  distance = [math.inf for i in range (len(Graph))] 
  distance[source] = 0 
  Q = [False] * len(Graph) # caminhos testados
 
  #tests all vertices looking for min
  for run in range(len(Graph)):
    # gets the minimum vertex
    u = distMin(Graph,distance,Q)
    Q[u] = True
    # tests sub-paths for neighbors of v looking for min
    for v in range(len(Graph)):
      # if a new min path has been found update
        if Graph[u][v] > 0 and Q[v] == False and distance[v] > distance[u] +Graph[u][v]:
            distance[v] = distance[u] + Graph[u][v]

  return distance



##Matrizes de Adjacência

$Teorema $ $1$:  Multiplicando uma matriz de adjacência $A_{nxn}$, de um grafo sem pesos, por ela mesmo $k$ vezes observamos que o matriz obtida possui ao número de caminhos (distintos) comprimento $k$ entre os vértices $(i,j)$ de $A_{ij}$ .

¹ A prova por indução para o $Teorema$ $1$ pode ser encontrada no arquivo do docs. 

O objetivo aqui será mostrar graficamente.

Com o grafo abaixo : 
> ![grafo1](https://i.imgur.com/Gq2xemI.png)

>Onde a matriz de adjacência é :
> $$A(G)_{6x6} = \begin{bmatrix}
 0 & 1  & 0 & 0 & 0& 0 \\ 
 0 & 0  & 1 & 0 & 0& 0 \\ 
 0 & 0  & 0 & 1 & 0& 0 \\ 
 0 & 0  & 0 & 0 & 1& 0 \\
 0 & 0  & 0 & 0 & 0& 1 \\
 0 & 0  & 0 & 0 & 0& 0 \\
\end{bmatrix}$$

>Fazendo : 

$$A*A = A^{2} $$ 
$$ onde \ k = 2 $$
>temos que : 

>>>$$A^{2}  = \qquad\begin{bmatrix}
 0 & 1  & 0 & 0 & 0& 0 \\ 
 0 & 0  & 1 & 0 & 0& 0 \\ 
 0 & 0  & 0 & 1 & 0& 0 \\ 
 0 & 0  & 0 & 0 & 1& 0 \\
 0 & 0  & 0 & 0 & 0& 1 \\
 0 & 0  & 0 & 0 & 0& 0 \\
\end{bmatrix} \quad * \quad\begin{bmatrix}
 0 & 1  & 0 & 0 & 0& 0 \\ 
 0 & 0  & 1 & 0 & 0& 0 \\ 
 0 & 0  & 0 & 1 & 0& 0 \\ 
 0 & 0  & 0 & 0 & 1& 0 \\
 0 & 0  & 0 & 0 & 0& 1 \\
 0 & 0  & 0 & 0 & 0& 0 \\
\end{bmatrix} $$

>Encontraremos os caminhos de tamanho 2 no grafo( arestas em vermelho)


>>> $$   \quad  A^{2}  = \begin{bmatrix}
0&0&1&0&0&0 \\
0&0&0&1&0&0 \\
0&0&0&0&1&0 \\
0&0&0&0&0&1 \\
0&0&0&0&0&0 \\
0&0&0&0&0&0 
\end{bmatrix}_{(6x6)} $$

> ![grafo2](https://i.imgur.com/L8UC5Rb.png)

>Onde cada entrada $i$ e $j$  da matriz $A^{2}$ corresponde ao número de caminhos de comprimento $k$  , onde $k=2$ .


###Repeated squaring method using min-plus

>Apesar do método anterior ser útil para encontrar o menor caminho em grafos que nao possuam peso, ele necessita de algumas alterações para que possa resolver o problema APSP em grafos com peso. 

>Para isso utilizaremos uma técnica de programação dinâmica (PD) e min-plus product.
>>A PD  é utilizada salvando os valores na matriz e comparando com ela mesmo.Já o min-plus product consiste em substituírmos o sinal de * por + e pelo operação de minimo.

>> Como por exemplo , dado duas matrizes A e B a * delas é  :
>> $$C = (c_{ij}) = A * B$$

>>$$ (c_{ij}) =  min_{k =1 }^{n} (a_{ik}+b_{kj})  $$

>Denotaremos $D(k)$ onde $k$  assumirá a quantidade de vezes que multiplicaremos a matriz $A$ $$A^{k} =A * A* A * ... *A$$
>Tentarei demonstrar intuitivamente o porque de ser usado min-plus 

>Intuitivamente : 
>>Dada o grafo abaixo :

>>>>>>>>![grafo](https://i.imgur.com/9To3ntZ.png)

>> Cuja matriz de adjacência é  :

$$A =  \begin{bmatrix}
 0 & 5  & \infty & \infty \\ 
 \infty &  0 & 1 & \infty \\ 
 8 & \infty  & 0 & 3 \\ 
 2 & \infty & \infty  & 0
\end{bmatrix}$$


>> Para encontrarmos o menor caminho nesse grafo primeiro faremos $A*A$ utilizando min-plus product

$$D(2) = A^{2}=  \begin{bmatrix}
 0 & 5  & \infty & \infty \\ 
 \infty &  0 & 1 & \infty \\ 
 8 & \infty  & 0 & 3 \\ 
 2 & \infty & \infty  & 0
\end{bmatrix}  * \begin{bmatrix}
 0 & 5  & \infty & \infty \\ 
 \infty &  0 & 1 & \infty \\ 
 8 & \infty  & 0 & 3 \\ 
 2 & \infty & \infty  & 0
\end{bmatrix}$$
>>Utilizamos o mesmo processo de multiplicação de matrizes, fazendo linha * coluna, no entanto usando min-plus.
>>> obs : Para cada $linha*coluna$, pegaremos o menor valor obtido da soma de cada elemento.
>>> Na primeira $linha *coluna$ teriamos que selecionar o minimo entre {${0+0,5 + \infty, \infty + 8, \infty+2}$} o que nos daria o resultado $0$.

>>Calculando a primeira linha da matriz $D(2)$
>>>$$ (d_{00}) =  min_{k =0 }^{4} (a_{0k} + a_{k0})  = 0 $$ 
>>>$$ (d_{01}) =  min_{k =0}^{4} (a_{1k} + a_{k1})  = 5 $$
>>>$$ (d_{02}) =  min_{k =0}^{4} (a_{2k} + a_{k2})  = 6 $$
>>>$$ (d_{03}) =  min_{k =0 }^{4} (a_{3k} + a_{k3})  = \infty$$

>>>$$D(2)=  \begin{bmatrix}
 0 & 5  & 6 & \infty \\ 
  9&  0 & 1 & 4 \\ 
 5 & 12  & 0 & 3 \\ 
 2 & 7 & \infty  & 0
\end{bmatrix}$$

>>Contudo, olhando no grafo, podemos reparar que essa matriz nao possui todos os caminhos mais curtos.Isso se dá porque nem sempre o caminho mais direto é o menos custoso. Assim, rodariamos o algorítmo novamente com $D(3)$¹ e veriamos, por exemplo, que o elemento $a_{03}$ alcançaria menor caminho. 

>>>$$ (d_{03}) =  min_{k =0 }^{4} (a_{3k} + a_{k3})  = 9$$

>> O algoritmo é rodado $k$ vezes, onde $k=len(V)$², para encontrarmos o caminho mais curto.

>> A PD³ é utilizada para conseguirmos salvar sempre o menor caminho, por mais que eu possa encontrar em D(3) um caminho com maior custo, teremos salvo em uma matriz se esse valor é maior ou menor que o anterior e guardaremos o menor sempre.

>>A matriz final do exemplo ficaria :
$$ \begin{bmatrix}
 0 & 5  & 6 & 9 \\ 
 6 &  0 & 1 & 4 \\ 
 5 & 10  & 0 & 3 \\ 
 2 & 7 & 8  & 0
\end{bmatrix}$$

>Concluindo :
>>Podemos ver que o algorítmo funciona pois ele parte da premissa de sempre salvar a soma do menor caminho entre dois vértices e ele testa todos os caminhos possiveis(ao ser rodado a mesma quantidade de vezes que o o número de vertices) pois faz uso do $Teorema1$ .Com o $Teorema1$ e rodando ele k vezes conseguimos garantir que ele veja os caminhos de tamanho $1..k$$ 



¹ o Algortimo é executado novamente entretanto os valores mínimos são sempre preservados.

² k é igual o número de vértices do grafo.

³ PD : forma abreviada de Programação Dinamica








In [28]:
#Multiplication with min-plus product and dynamic programming
#diagonal must be 0
#non-adjacent inf
#feito da mesma forma que um algoritmo de produto retangular, entretanto, na parte da multiplicação 
#trocamos * por + e min
def specialMultiply(A,B):
  n = len(A)
  #C matrix auxiliar 
  C = np.zeros((n,n))
  
  for i in range(n):
    for j in range(n):
      #inicializacao do vetor auxiliar
      C[i,j] = math.inf
      for k in range(0,n):
        #PD, procuro sempre o menor valor entre a soma do valor das arestas entre os vertices e o que já tinhamos visto anteriormente
        C[i,j] = min(A[i][k]+B[k][j],C[i,j]) #min-plus algebra
  return C


As rotinas abaixo servem para calcular $D(1) ...D(k)$¹ retornando k -1 (para testar todos os caminhos de comprimento diferete) , o que , como explicado anteriormente, possibilita achar o menor caminho 

Input : Grafo , matriz de adjacência 

Output :  Matriz com o caminho mais curto 



¹ k é a quantidade de vertices do grafo

In [29]:
def calculateDfaster(W):
  n = len(W)
  D = []
  D.insert(0,W)
  D.insert(1,W)
  m = 1
  while m < n -1 :
    D.insert((2*m),(specialMultiply(D[m],D[m])))
    m = 2*m
  return D[len(D) -1]

In [30]:
def calculateDslower(W) :
  L = []
  L.insert(0,W)
  for m in range(1,len(W)):
    L.insert(m,(specialMultiply(L[m-1],W)))
  return L[m-1]


##INPUT

Uma matriz de adjacência  $nxn$, onde a distância de um vértice $u$ até o vértice  $g$ onde nao possuem arestas os ligando é $\infty$, e, a distância de $u$ atéw $u$ caso nao seja conectado com si mesmo é $0$

####Matematicamente falando  : 

> $G = (V,E)$

> $ A(G)_{nxn} ,
\begin{gather*}
  a_{ij} {=}
  \begin{cases}
  w & \text{Peso da aresta de  $j$ até $i$ caso exista.}\\
  \infty & \text{Não existindo aresta entre $j$ até $i$ .}\\
  0 & \text{Não sendo conectado a si mesmo.}
  \end{cases}
\end{gather*}$




####Exemplo :
> $A(G)_{4x4} = \begin{bmatrix}
 0 & 5  & \infty & \infty \\ 
 \infty &  0 & 1 & \infty \\ 
 8 & \infty  & 0 & 3 \\ 
 2 & \infty & \infty  & 0
\end{bmatrix}$ 


> ![grafo](https://i.imgur.com/9To3ntZ.png)





 


In [31]:
# graph inputed
g = [
    [0,5,math.inf,math.inf],
    [math.inf,0,1,math.inf],
    [8, math.inf,0,3],
    [2,math.inf,math.inf,0]
]
#Repeated Squaring
print("Repeated Squaring mode")
print("Slow mode\n",calculateDslower(g))
print("Faster mode \n",calculateDfaster(g))
#Dijkstra
print("Dijkstra")
print(dijkstra(g,0))
print(dijkstra(g,1))
print(dijkstra(g,2))
print(dijkstra(g,3))



Repeated Squaring mode
Slow mode
 [[ 0.  5.  6.  9.]
 [ 6.  0.  1.  4.]
 [ 5. 10.  0.  3.]
 [ 2.  7.  8.  0.]]
Faster mode 
 [[ 0.  5.  6.  9.]
 [ 6.  0.  1.  4.]
 [ 5. 10.  0.  3.]
 [ 2.  7.  8.  0.]]
Dijkstra
[0, 5, 6, 9]
[6, 0, 1, 4]
[5, 10, 0, 3]
[2, 7, 8, 0]


##Comparações
>O algorítmo do Dijkstra possuí diversas formas de implementação(lista de prioriade, heap de fibonacci,...) o que faz com que possamos obter diferentes valores para sua complexidade. Podemos ter de $O(V³)$ até $O(E + V log V)$ (utilizando heap de fibonacci).

>Já com o algorítmo de potenciação de matrizes apresentado aqui teremos $O(V^{w})$ com $w= 3$, sendo $w$ a complexidade para multiplicação de matrizes. Entretanto estão sempre tentando melhorar o processo de multiplicação de matrizes e , hoje, um dos algorítmos mais novos e eficientes nos da $w=2.376$.

>Outros algorítmos que utilizam multiplicação de matriz para resolver APSP  conseguem ser cada vez mais rapidos, temos o algorítmo de Chan ’07 com complexidade de $n³(log log n)³/ (log n)²$

>Dessa forma, vemos que o algorítmo Dijkstra quase sempre será melhor, contudo, isso depende da implementação utilizada. 

In [34]:


print("Repeated Squaring mode")

start_time = time.time()
print("Slow mode\n",calculateDslower(g))
print("---time for slow mode :   %s seconds ---" % (time.time() - start_time))

start_time = time.time()
print("Faster mode \n",calculateDfaster(g))
print("---time for faster mode :   %s seconds ---" % (time.time() - start_time))

#Dijkstra
print("Dijkstra")
start_time = time.time()
print(dijkstra(g,0))
print(dijkstra(g,1))
print(dijkstra(g,2))
print(dijkstra(g,3))
print("---time for dijkstra :   %s seconds ---" % (time.time() - start_time))

Repeated Squaring mode
Slow mode
 [[ 0.  5.  6.  9.]
 [ 6.  0.  1.  4.]
 [ 5. 10.  0.  3.]
 [ 2.  7.  8.  0.]]
---time for slow mode :   0.001775979995727539 seconds ---
Faster mode 
 [[ 0.  5.  6.  9.]
 [ 6.  0.  1.  4.]
 [ 5. 10.  0.  3.]
 [ 2.  7.  8.  0.]]
---time for faster mode :   0.0012688636779785156 seconds ---
Dijkstra
[0, 5, 6, 9]
[6, 0, 1, 4]
[5, 10, 0, 3]
[2, 7, 8, 0]
---time for dijkstra :   0.0008227825164794922 seconds ---


Observação :

o tempo de execução acima varia bastante.Entretanto, na maioria dos resultados apresentados temos Dijkstra em primeiro, Faster mode em segundo e slower em terceiro, as vezes o faster-mode fica na frente do Dijktra.